### ISSUE TITLE
Organizar el wiki

### ISSUE THREAD

**Issue by norman-ipn** [EdgarRamirezFuentes/Proyecto-Final-Estructuras-De-Datos-ESCOM#2]
- Hay que organizar la información en la wiki.

**Comment by EdgarRamirezFuentes** [comment]
Profe, ya organicé la wiki e integré algunos análisis de la elección de la estructura de datos.
No tardaré mucho en hacer los últimos análisis faltantes (Tablas Hash y Árboles).
Favor de revisar los cambios y notificar cualquier modificación que se requiera.

**Comment by EdgarRamirezFuentes** [comment]
Wiki organizada.
