### ISSUE TITLE
Apoyo para esconder las ventanas.

### ISSUE THREAD

**Issue by EdgarRamirezFuentes** [EdgarRamirezFuentes/Proyecto-Final-Estructuras-De-Datos-ESCOM#3]
Buenos días.
Profesor, ya he logrado enlazar el evento "clicked" de cada botón de la ventana principal para que muestre la interfaz seleccionada.
El problema es que no he encontrado alguna función para poner en el callback que me ayude a esconder la ventana.
Me podría recomendar algo para implementarlo.
El código ya está en el repositorio, en la carpeta UI.

![Captura de pantalla de 2019-10-26 19-05-57](https://user-images.githubusercontent.com/50359137/67627543-bb370600-f823-11e9-87e6-ac4c9fdcd6a5.png)

**Comment by norman-ipn** [comment]
resuelto en asesoría.
